apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prox
  name: prox
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prox
  template:
    metadata:
      labels:
        app: prox
    spec:
      containers:
      - image: nginx-proxy:3
        imagePullPolicy: IfNotPresent
        name: nginx-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
