apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: fluent-bit
  name: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fluent-bit
    spec:
      # securityContext:
      #   runAsUser: 0
      serviceAccountName: fluent-bit
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # - name: mnt
        #   hostPath:
        #     path: /mnt
        - name: journal
          hostPath:
            path: /run/log/journal
      containers:
      - image: docker.io/fluent/fluent-bit:3.1.9
        name: fluent-bit
        ports:
          - containerPort: 2020
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        volumeMounts:
          - name: fluent-bit-config
            mountPath: /fluent-bit/etc/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          # - name: mnt
          #   mountPath: /mnt
          #   readOnly: true
          - name: journal
            mountPath: /run/log/journal
        resources: {}

