kind: PersistentVolume
apiVersion: v1
metadata:
  name: 'test-nginx-pv'
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/test-nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
