apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-server-config
data:
  redis-config: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-server
  name: redis-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-server-config
            items:
            - key: redis-config
              path: redis.conf
      containers:
      - image: docker.io/library/redis:7.2.5
        imagePullPolicy: IfNotPresent
        name: redis-server
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
            ephemeral-storage: "500Mi"
