apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  ttlSecondsAfterFinished: 21600
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: test
        image: busybox
        
        #command: ["echo", "hello world", "&&", "echo", "message 2"]
        #command: ["echo 'hello world' && echo 'message 2'"]
        #command: ["/bin/sh","-c","echo 'here111' && echo 'here222' && ls /"]
        command:
        - /bin/sh
        - -c
        - echo "here1113" && echo "here2223"
        resources:
          limits:
            memory: 200Mi
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
