apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-forecast-webapi-config
  namespace: default
data:
  appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "AllowedHosts": "*",
        "Serilog": {
            "Using": [ "Serilog.Sinks.File", "Serilog.Enrichers.Environment" ],
            "MinimumLevel": {
                "Default": "Information"
            },
            "WriteTo": [
                {
                    "Name": "Console",
                    "Args": {
                        "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Literate, Serilog.Sinks.Console",
                        //"outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}[{Timestamp:HH:mm:ss} {Level:u3}] {Properties} <s:{SourceContext}>{NewLine}{Exception}",
                        //"outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <m:{MachineName}> <s:{SourceContext}>{NewLine}{Exception}",
                        //"outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}",
                        "applyThemeToRedirectedOutput": true
                    }
                }
            ],
            "Enrich": [ "FromLogContext", "WithMachineName" ],
            "Properties": {
                "ApplicationName": "WeatherForecastApi"
            }
        },
        "Features": {
            "UseExample": true
        },
        "Example": {
            "Setting1": "ExampleSetting1Value"
        }
    }
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30    
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice    
