apiVersion: v1
kind: Secret
metadata:
  name: weather-forecast-webapi-secret
  namespace: default
type: Opaque
data:
  Db1ConnectionString: "Db1ConnectionStringValue"
  Db2ConnectionString: "Db2ConnectionStringValue"
  .secret-file: dmFsdWUtMg0KDQo=
stringData:
  .appsettings.secrets.json: |
    {
        "ConnectionStrings": {
            "WareLogix": "Server=(localdb)\\MSSQLLocalDB;Integrated Security=true;Initial Catalog=warelogix",
            "AdventureWorks": "Server=(localdb)\\MSSQLLocalDB;Integrated Security=true;Initial Catalog=AdventureWorks"
        }
    }
