apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\zhixian\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sun, 13 Oct 2024 11:23:01 +08
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://172.25.125.214:8443
  name: contoso
- cluster:
    certificate-authority: C:\Users\zhixian\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Wed, 09 Oct 2024 16:14:58 +08
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://172.25.113.128:8443
  name: minikube
contexts:
- context:
    cluster: contoso
    extensions:
    - extension:
        last-update: Sun, 13 Oct 2024 11:23:01 +08
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: contoso
  name: contoso
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 09 Oct 2024 16:14:58 +08
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: contoso
  user:
    client-certificate: C:\Users\zhixian\.minikube\profiles\contoso\client.crt
    client-key: C:\Users\zhixian\.minikube\profiles\contoso\client.key
- name: minikube
  user:
    client-certificate: C:\Users\zhixian\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\zhixian\.minikube\profiles\minikube\client.key
