//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class CreateBucket {
    
    private string bucketField;
    
    private Grant[] accessControlListField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class Grant {
    
    private Grantee granteeField;
    
    private Permission permissionField;
    
    /// <remarks/>
    public Grantee Grantee {
        get {
            return this.granteeField;
        }
        set {
            this.granteeField = value;
        }
    }
    
    /// <remarks/>
    public Permission Permission {
        get {
            return this.permissionField;
        }
        set {
            this.permissionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalUser))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCustomerByEmail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public abstract partial class Grantee {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class CopyObjectResult {
    
    private System.DateTime lastModifiedField;
    
    private string eTagField;
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class ListAllMyBucketsEntry {
    
    private string nameField;
    
    private System.DateTime creationDateField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class ListAllMyBucketsResult {
    
    private CanonicalUser ownerField;
    
    private ListAllMyBucketsEntry[] bucketsField;
    
    /// <remarks/>
    public CanonicalUser Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Bucket", IsNullable=false)]
    public ListAllMyBucketsEntry[] Buckets {
        get {
            return this.bucketsField;
        }
        set {
            this.bucketsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class CanonicalUser : User {
    
    private string idField;
    
    private string displayNameField;
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalUser))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCustomerByEmail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public abstract partial class User : Grantee {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class AmazonCustomerByEmail : User {
    
    private string emailAddressField;
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class DeleteMarkerEntry {
    
    private string keyField;
    
    private string versionIdField;
    
    private bool isLatestField;
    
    private System.DateTime lastModifiedField;
    
    private CanonicalUser ownerField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string VersionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    public bool IsLatest {
        get {
            return this.isLatestField;
        }
        set {
            this.isLatestField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    public CanonicalUser Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class VersionEntry {
    
    private string keyField;
    
    private string versionIdField;
    
    private bool isLatestField;
    
    private System.DateTime lastModifiedField;
    
    private string eTagField;
    
    private long sizeField;
    
    private CanonicalUser ownerField;
    
    private StorageClass storageClassField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string VersionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    public bool IsLatest {
        get {
            return this.isLatestField;
        }
        set {
            this.isLatestField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
    
    /// <remarks/>
    public long Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public CanonicalUser Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    public StorageClass StorageClass {
        get {
            return this.storageClassField;
        }
        set {
            this.storageClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public enum StorageClass {
    
    /// <remarks/>
    STANDARD,
    
    /// <remarks/>
    REDUCED_REDUNDANCY,
    
    /// <remarks/>
    GLACIER,
    
    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class ListVersionsResult {
    
    private MetadataEntry[] metadataField;
    
    private string nameField;
    
    private string prefixField;
    
    private string keyMarkerField;
    
    private string versionIdMarkerField;
    
    private string nextKeyMarkerField;
    
    private string nextVersionIdMarkerField;
    
    private int maxKeysField;
    
    private string delimiterField;
    
    private bool isTruncatedField;
    
    private object[] itemsField;
    
    private PrefixEntry[] commonPrefixesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string KeyMarker {
        get {
            return this.keyMarkerField;
        }
        set {
            this.keyMarkerField = value;
        }
    }
    
    /// <remarks/>
    public string VersionIdMarker {
        get {
            return this.versionIdMarkerField;
        }
        set {
            this.versionIdMarkerField = value;
        }
    }
    
    /// <remarks/>
    public string NextKeyMarker {
        get {
            return this.nextKeyMarkerField;
        }
        set {
            this.nextKeyMarkerField = value;
        }
    }
    
    /// <remarks/>
    public string NextVersionIdMarker {
        get {
            return this.nextVersionIdMarkerField;
        }
        set {
            this.nextVersionIdMarkerField = value;
        }
    }
    
    /// <remarks/>
    public int MaxKeys {
        get {
            return this.maxKeysField;
        }
        set {
            this.maxKeysField = value;
        }
    }
    
    /// <remarks/>
    public string Delimiter {
        get {
            return this.delimiterField;
        }
        set {
            this.delimiterField = value;
        }
    }
    
    /// <remarks/>
    public bool IsTruncated {
        get {
            return this.isTruncatedField;
        }
        set {
            this.isTruncatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeleteMarker", typeof(DeleteMarkerEntry))]
    [System.Xml.Serialization.XmlElementAttribute("Version", typeof(VersionEntry))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CommonPrefixes")]
    public PrefixEntry[] CommonPrefixes {
        get {
            return this.commonPrefixesField;
        }
        set {
            this.commonPrefixesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class MetadataEntry {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class PrefixEntry {
    
    private string prefixField;
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class ListEntry {
    
    private string keyField;
    
    private System.DateTime lastModifiedField;
    
    private string eTagField;
    
    private long sizeField;
    
    private CanonicalUser ownerField;
    
    private StorageClass storageClassField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
    
    /// <remarks/>
    public long Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public CanonicalUser Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    public StorageClass StorageClass {
        get {
            return this.storageClassField;
        }
        set {
            this.storageClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class ListBucketResult {
    
    private MetadataEntry[] metadataField;
    
    private string nameField;
    
    private string prefixField;
    
    private string markerField;
    
    private string nextMarkerField;
    
    private int maxKeysField;
    
    private string delimiterField;
    
    private bool isTruncatedField;
    
    private ListEntry[] contentsField;
    
    private PrefixEntry[] commonPrefixesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string Marker {
        get {
            return this.markerField;
        }
        set {
            this.markerField = value;
        }
    }
    
    /// <remarks/>
    public string NextMarker {
        get {
            return this.nextMarkerField;
        }
        set {
            this.nextMarkerField = value;
        }
    }
    
    /// <remarks/>
    public int MaxKeys {
        get {
            return this.maxKeysField;
        }
        set {
            this.maxKeysField = value;
        }
    }
    
    /// <remarks/>
    public string Delimiter {
        get {
            return this.delimiterField;
        }
        set {
            this.delimiterField = value;
        }
    }
    
    /// <remarks/>
    public bool IsTruncated {
        get {
            return this.isTruncatedField;
        }
        set {
            this.isTruncatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contents")]
    public ListEntry[] Contents {
        get {
            return this.contentsField;
        }
        set {
            this.contentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CommonPrefixes")]
    public PrefixEntry[] CommonPrefixes {
        get {
            return this.commonPrefixesField;
        }
        set {
            this.commonPrefixesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class PutObjectResult {
    
    private string eTagField;
    
    private System.DateTime lastModifiedField;
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetObjectResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class Result {
    
    private Status statusField;
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class Status {
    
    private int codeField;
    
    private string descriptionField;
    
    /// <remarks/>
    public int Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class GetObjectResult : Result {
    
    private MetadataEntry[] metadataField;
    
    private byte[] dataField;
    
    private System.DateTime lastModifiedField;
    
    private string eTagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class AccessControlPolicy {
    
    private CanonicalUser ownerField;
    
    private Grant[] accessControlListField;
    
    /// <remarks/>
    public CanonicalUser Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class LoggingSettings {
    
    private string targetBucketField;
    
    private string targetPrefixField;
    
    private Grant[] targetGrantsField;
    
    /// <remarks/>
    public string TargetBucket {
        get {
            return this.targetBucketField;
        }
        set {
            this.targetBucketField = value;
        }
    }
    
    /// <remarks/>
    public string TargetPrefix {
        get {
            return this.targetPrefixField;
        }
        set {
            this.targetPrefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] TargetGrants {
        get {
            return this.targetGrantsField;
        }
        set {
            this.targetGrantsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class BucketLoggingStatus {
    
    private LoggingSettings loggingEnabledField;
    
    /// <remarks/>
    public LoggingSettings LoggingEnabled {
        get {
            return this.loggingEnabledField;
        }
        set {
            this.loggingEnabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class CreateBucketResult {
    
    private string bucketNameField;
    
    /// <remarks/>
    public string BucketName {
        get {
            return this.bucketNameField;
        }
        set {
            this.bucketNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public partial class Group : Grantee {
    
    private string uRIField;
    
    /// <remarks/>
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public enum Permission {
    
    /// <remarks/>
    READ,
    
    /// <remarks/>
    WRITE,
    
    /// <remarks/>
    READ_ACP,
    
    /// <remarks/>
    WRITE_ACP,
    
    /// <remarks/>
    FULL_CONTROL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class CreateBucketResponse {
    
    private CreateBucketResult createBucketReturnField;
    
    /// <remarks/>
    public CreateBucketResult CreateBucketReturn {
        get {
            return this.createBucketReturnField;
        }
        set {
            this.createBucketReturnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class DeleteBucket {
    
    private string bucketField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class DeleteBucketResponse {
    
    private Status deleteBucketResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeleteBucketResponse")]
    public Status DeleteBucketResponse1 {
        get {
            return this.deleteBucketResponse1Field;
        }
        set {
            this.deleteBucketResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetBucketLoggingStatus {
    
    private string bucketField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetBucketLoggingStatusResponse {
    
    private BucketLoggingStatus getBucketLoggingStatusResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetBucketLoggingStatusResponse")]
    public BucketLoggingStatus GetBucketLoggingStatusResponse1 {
        get {
            return this.getBucketLoggingStatusResponse1Field;
        }
        set {
            this.getBucketLoggingStatusResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetBucketLoggingStatus {
    
    private string bucketField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    private BucketLoggingStatus bucketLoggingStatusField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
    
    /// <remarks/>
    public BucketLoggingStatus BucketLoggingStatus {
        get {
            return this.bucketLoggingStatusField;
        }
        set {
            this.bucketLoggingStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetBucketLoggingStatusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObjectAccessControlPolicy {
    
    private string bucketField;
    
    private string keyField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObjectAccessControlPolicyResponse {
    
    private AccessControlPolicy getObjectAccessControlPolicyResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetObjectAccessControlPolicyResponse")]
    public AccessControlPolicy GetObjectAccessControlPolicyResponse1 {
        get {
            return this.getObjectAccessControlPolicyResponse1Field;
        }
        set {
            this.getObjectAccessControlPolicyResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetBucketAccessControlPolicy {
    
    private string bucketField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetBucketAccessControlPolicyResponse {
    
    private AccessControlPolicy getBucketAccessControlPolicyResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetBucketAccessControlPolicyResponse")]
    public AccessControlPolicy GetBucketAccessControlPolicyResponse1 {
        get {
            return this.getBucketAccessControlPolicyResponse1Field;
        }
        set {
            this.getBucketAccessControlPolicyResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetObjectAccessControlPolicy {
    
    private string bucketField;
    
    private string keyField;
    
    private Grant[] accessControlListField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetObjectAccessControlPolicyResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetBucketAccessControlPolicy {
    
    private string bucketField;
    
    private Grant[] accessControlListField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class SetBucketAccessControlPolicyResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObject {
    
    private string bucketField;
    
    private string keyField;
    
    private bool getMetadataField;
    
    private bool getDataField;
    
    private bool inlineDataField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public bool GetMetadata {
        get {
            return this.getMetadataField;
        }
        set {
            this.getMetadataField = value;
        }
    }
    
    /// <remarks/>
    public bool GetData {
        get {
            return this.getDataField;
        }
        set {
            this.getDataField = value;
        }
    }
    
    /// <remarks/>
    public bool InlineData {
        get {
            return this.inlineDataField;
        }
        set {
            this.inlineDataField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObjectResponse {
    
    private GetObjectResult getObjectResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetObjectResponse")]
    public GetObjectResult GetObjectResponse1 {
        get {
            return this.getObjectResponse1Field;
        }
        set {
            this.getObjectResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObjectExtended {
    
    private string bucketField;
    
    private string keyField;
    
    private bool getMetadataField;
    
    private bool getDataField;
    
    private bool inlineDataField;
    
    private long byteRangeStartField;
    
    private bool byteRangeStartFieldSpecified;
    
    private long byteRangeEndField;
    
    private bool byteRangeEndFieldSpecified;
    
    private System.DateTime ifModifiedSinceField;
    
    private bool ifModifiedSinceFieldSpecified;
    
    private System.DateTime ifUnmodifiedSinceField;
    
    private bool ifUnmodifiedSinceFieldSpecified;
    
    private string[] ifMatchField;
    
    private string[] ifNoneMatchField;
    
    private bool returnCompleteObjectOnConditionFailureField;
    
    private bool returnCompleteObjectOnConditionFailureFieldSpecified;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public bool GetMetadata {
        get {
            return this.getMetadataField;
        }
        set {
            this.getMetadataField = value;
        }
    }
    
    /// <remarks/>
    public bool GetData {
        get {
            return this.getDataField;
        }
        set {
            this.getDataField = value;
        }
    }
    
    /// <remarks/>
    public bool InlineData {
        get {
            return this.inlineDataField;
        }
        set {
            this.inlineDataField = value;
        }
    }
    
    /// <remarks/>
    public long ByteRangeStart {
        get {
            return this.byteRangeStartField;
        }
        set {
            this.byteRangeStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ByteRangeStartSpecified {
        get {
            return this.byteRangeStartFieldSpecified;
        }
        set {
            this.byteRangeStartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long ByteRangeEnd {
        get {
            return this.byteRangeEndField;
        }
        set {
            this.byteRangeEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ByteRangeEndSpecified {
        get {
            return this.byteRangeEndFieldSpecified;
        }
        set {
            this.byteRangeEndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime IfModifiedSince {
        get {
            return this.ifModifiedSinceField;
        }
        set {
            this.ifModifiedSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IfModifiedSinceSpecified {
        get {
            return this.ifModifiedSinceFieldSpecified;
        }
        set {
            this.ifModifiedSinceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime IfUnmodifiedSince {
        get {
            return this.ifUnmodifiedSinceField;
        }
        set {
            this.ifUnmodifiedSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IfUnmodifiedSinceSpecified {
        get {
            return this.ifUnmodifiedSinceFieldSpecified;
        }
        set {
            this.ifUnmodifiedSinceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IfMatch")]
    public string[] IfMatch {
        get {
            return this.ifMatchField;
        }
        set {
            this.ifMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IfNoneMatch")]
    public string[] IfNoneMatch {
        get {
            return this.ifNoneMatchField;
        }
        set {
            this.ifNoneMatchField = value;
        }
    }
    
    /// <remarks/>
    public bool ReturnCompleteObjectOnConditionFailure {
        get {
            return this.returnCompleteObjectOnConditionFailureField;
        }
        set {
            this.returnCompleteObjectOnConditionFailureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReturnCompleteObjectOnConditionFailureSpecified {
        get {
            return this.returnCompleteObjectOnConditionFailureFieldSpecified;
        }
        set {
            this.returnCompleteObjectOnConditionFailureFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class GetObjectExtendedResponse {
    
    private GetObjectResult getObjectResponseField;
    
    /// <remarks/>
    public GetObjectResult GetObjectResponse {
        get {
            return this.getObjectResponseField;
        }
        set {
            this.getObjectResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class PutObject {
    
    private string bucketField;
    
    private string keyField;
    
    private MetadataEntry[] metadataField;
    
    private long contentLengthField;
    
    private Grant[] accessControlListField;
    
    private StorageClass storageClassField;
    
    private bool storageClassFieldSpecified;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    public long ContentLength {
        get {
            return this.contentLengthField;
        }
        set {
            this.contentLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public StorageClass StorageClass {
        get {
            return this.storageClassField;
        }
        set {
            this.storageClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StorageClassSpecified {
        get {
            return this.storageClassFieldSpecified;
        }
        set {
            this.storageClassFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class PutObjectResponse {
    
    private PutObjectResult putObjectResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PutObjectResponse")]
    public PutObjectResult PutObjectResponse1 {
        get {
            return this.putObjectResponse1Field;
        }
        set {
            this.putObjectResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class PutObjectInline {
    
    private string bucketField;
    
    private string keyField;
    
    private MetadataEntry[] metadataField;
    
    private byte[] dataField;
    
    private long contentLengthField;
    
    private Grant[] accessControlListField;
    
    private StorageClass storageClassField;
    
    private bool storageClassFieldSpecified;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public long ContentLength {
        get {
            return this.contentLengthField;
        }
        set {
            this.contentLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public StorageClass StorageClass {
        get {
            return this.storageClassField;
        }
        set {
            this.storageClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StorageClassSpecified {
        get {
            return this.storageClassFieldSpecified;
        }
        set {
            this.storageClassFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class PutObjectInlineResponse {
    
    private PutObjectResult putObjectInlineResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PutObjectInlineResponse")]
    public PutObjectResult PutObjectInlineResponse1 {
        get {
            return this.putObjectInlineResponse1Field;
        }
        set {
            this.putObjectInlineResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class DeleteObject {
    
    private string bucketField;
    
    private string keyField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class DeleteObjectResponse {
    
    private Status deleteObjectResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeleteObjectResponse")]
    public Status DeleteObjectResponse1 {
        get {
            return this.deleteObjectResponse1Field;
        }
        set {
            this.deleteObjectResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class ListBucket {
    
    private string bucketField;
    
    private string prefixField;
    
    private string markerField;
    
    private int maxKeysField;
    
    private bool maxKeysFieldSpecified;
    
    private string delimiterField;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string Marker {
        get {
            return this.markerField;
        }
        set {
            this.markerField = value;
        }
    }
    
    /// <remarks/>
    public int MaxKeys {
        get {
            return this.maxKeysField;
        }
        set {
            this.maxKeysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxKeysSpecified {
        get {
            return this.maxKeysFieldSpecified;
        }
        set {
            this.maxKeysFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Delimiter {
        get {
            return this.delimiterField;
        }
        set {
            this.delimiterField = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class ListBucketResponse {
    
    private ListBucketResult listBucketResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListBucketResponse")]
    public ListBucketResult ListBucketResponse1 {
        get {
            return this.listBucketResponse1Field;
        }
        set {
            this.listBucketResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class ListVersionsResponse {
    
    private ListVersionsResult listVersionsResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListVersionsResponse")]
    public ListVersionsResult ListVersionsResponse1 {
        get {
            return this.listVersionsResponse1Field;
        }
        set {
            this.listVersionsResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class ListAllMyBuckets {
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class ListAllMyBucketsResponse {
    
    private ListAllMyBucketsResult listAllMyBucketsResponse1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListAllMyBucketsResponse")]
    public ListAllMyBucketsResult ListAllMyBucketsResponse1 {
        get {
            return this.listAllMyBucketsResponse1Field;
        }
        set {
            this.listAllMyBucketsResponse1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class PostResponse {
    
    private string locationField;
    
    private string bucketField;
    
    private string keyField;
    
    private string eTagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string ETag {
        get {
            return this.eTagField;
        }
        set {
            this.eTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class CopyObject {
    
    private string sourceBucketField;
    
    private string sourceKeyField;
    
    private string destinationBucketField;
    
    private string destinationKeyField;
    
    private MetadataDirective metadataDirectiveField;
    
    private bool metadataDirectiveFieldSpecified;
    
    private MetadataEntry[] metadataField;
    
    private Grant[] accessControlListField;
    
    private System.DateTime copySourceIfModifiedSinceField;
    
    private bool copySourceIfModifiedSinceFieldSpecified;
    
    private System.DateTime copySourceIfUnmodifiedSinceField;
    
    private bool copySourceIfUnmodifiedSinceFieldSpecified;
    
    private string[] copySourceIfMatchField;
    
    private string[] copySourceIfNoneMatchField;
    
    private StorageClass storageClassField;
    
    private bool storageClassFieldSpecified;
    
    private string aWSAccessKeyIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string signatureField;
    
    private string credentialField;
    
    /// <remarks/>
    public string SourceBucket {
        get {
            return this.sourceBucketField;
        }
        set {
            this.sourceBucketField = value;
        }
    }
    
    /// <remarks/>
    public string SourceKey {
        get {
            return this.sourceKeyField;
        }
        set {
            this.sourceKeyField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationBucket {
        get {
            return this.destinationBucketField;
        }
        set {
            this.destinationBucketField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationKey {
        get {
            return this.destinationKeyField;
        }
        set {
            this.destinationKeyField = value;
        }
    }
    
    /// <remarks/>
    public MetadataDirective MetadataDirective {
        get {
            return this.metadataDirectiveField;
        }
        set {
            this.metadataDirectiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MetadataDirectiveSpecified {
        get {
            return this.metadataDirectiveFieldSpecified;
        }
        set {
            this.metadataDirectiveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata")]
    public MetadataEntry[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Grant[] AccessControlList {
        get {
            return this.accessControlListField;
        }
        set {
            this.accessControlListField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CopySourceIfModifiedSince {
        get {
            return this.copySourceIfModifiedSinceField;
        }
        set {
            this.copySourceIfModifiedSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CopySourceIfModifiedSinceSpecified {
        get {
            return this.copySourceIfModifiedSinceFieldSpecified;
        }
        set {
            this.copySourceIfModifiedSinceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CopySourceIfUnmodifiedSince {
        get {
            return this.copySourceIfUnmodifiedSinceField;
        }
        set {
            this.copySourceIfUnmodifiedSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CopySourceIfUnmodifiedSinceSpecified {
        get {
            return this.copySourceIfUnmodifiedSinceFieldSpecified;
        }
        set {
            this.copySourceIfUnmodifiedSinceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CopySourceIfMatch")]
    public string[] CopySourceIfMatch {
        get {
            return this.copySourceIfMatchField;
        }
        set {
            this.copySourceIfMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CopySourceIfNoneMatch")]
    public string[] CopySourceIfNoneMatch {
        get {
            return this.copySourceIfNoneMatchField;
        }
        set {
            this.copySourceIfNoneMatchField = value;
        }
    }
    
    /// <remarks/>
    public StorageClass StorageClass {
        get {
            return this.storageClassField;
        }
        set {
            this.storageClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StorageClassSpecified {
        get {
            return this.storageClassFieldSpecified;
        }
        set {
            this.storageClassFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AWSAccessKeyId {
        get {
            return this.aWSAccessKeyIdField;
        }
        set {
            this.aWSAccessKeyIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
public enum MetadataDirective {
    
    /// <remarks/>
    COPY,
    
    /// <remarks/>
    REPLACE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s3.amazonaws.com/doc/2006-03-01/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://s3.amazonaws.com/doc/2006-03-01/", IsNullable=false)]
public partial class CopyObjectResponse {
    
    private CopyObjectResult copyObjectResultField;
    
    /// <remarks/>
    public CopyObjectResult CopyObjectResult {
        get {
            return this.copyObjectResultField;
        }
        set {
            this.copyObjectResultField = value;
        }
    }
}
