apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: docker.io/library/sample-python:0.0.0.6
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        imagePullPolicy: IfNotPresent
        name: sample-python
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app/test.json
          name: sample-python-secrets-volume
          subPath: test.json
          readOnly: true
        - mountPath: /opt/app/.secrets.json
          name: sample-python2-secrets-volume
          subPath: secrets.json
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sample-python-secrets-volume
        secret:
          defaultMode: 420
          secretName: sample-python
          items:
          - key: test
            path: test.json
      - name: sample-python2-secrets-volume
        secret:
          defaultMode: 420
          secretName: sample-python2
          items:
          - key: secrets.json
            path: secrets.json