apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
data:
  9000: "default/example-go:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
data:
  53: "kube-system/kube-dns:53"